"""baseline schema

Revision ID: c1a7b0d4e2f1
Revises: 
Create Date: 2026-09-28 11:26:42.154425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a7b0d4e2f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('defect_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('page_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pixel_size_nm', sa.Float(), nullable=True),
    sa.Column('sizes_nm_json', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('histogram_filename', sa.String(length=300), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('measurement_type', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('extra_images_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysis_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('plot_type', sa.String(length=30), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('overall_analysis', sa.Text(), nullable=True),
    sa.Column('plot_filename', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('char_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('technique_name', sa.String(length=150), nullable=False),
    sa.Column('date_scheduled', sa.Date(), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('sample_prep', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('stored_filename', sa.String(length=300), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('technique_name', sa.String(length=150), nullable=True),
    sa.Column('x_column', sa.String(length=100), nullable=True),
    sa.Column('y_column', sa.String(length=100), nullable=True),
    sa.Column('fit_type', sa.String(length=30), nullable=True),
    sa.Column('fit_params', sa.Text(), nullable=True),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('plot_filename', sa.String(length=300), nullable=True),
    sa.Column('parse_delimiter', sa.String(length=20), nullable=True),
    sa.Column('parse_header_row', sa.Integer(), nullable=True),
    sa.Column('pixel_size_nm', sa.Float(), nullable=True),
    sa.Column('image_crop_bottom', sa.Integer(), nullable=True),
    sa.Column('preview_filename', sa.String(length=300), nullable=True),
    sa.Column('channel_type', sa.String(length=50), nullable=True),
    sa.Column('data_units', sa.String(length=20), nullable=True),
    sa.Column('height_data_filename', sa.String(length=300), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=True),
    sa.Column('imaging_notes', sa.Text(), nullable=True),
    sa.Column('spring_constant', sa.Float(), nullable=True),
    sa.Column('y_column_retract', sa.String(length=100), nullable=True),
    sa.Column('adhesion_force', sa.Float(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('simulation_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('entry_datetime', sa.DateTime(), nullable=False),
    sa.Column('exp_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('input_params', sa.Text(), nullable=True),
    sa.Column('output_results', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misc_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('research_topic', sa.String(length=200), nullable=False),
    sa.Column('journal', sa.String(length=50), nullable=True),
    sa.Column('paper_title', sa.String(length=300), nullable=True),
    sa.Column('paper_link', sa.String(length=500), nullable=True),
    sa.Column('pdf_filename', sa.String(length=300), nullable=True),
    sa.Column('key_facts', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overlay_plot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('fit_results_json', sa.Text(), nullable=True),
    sa.Column('plot_filename', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grant_name', sa.String(length=200), nullable=True),
    sa.Column('funding_start', sa.Date(), nullable=True),
    sa.Column('funding_end', sa.Date(), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['lab_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('deliverable', sa.String(length=300), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('equipment', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('linked_experiment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['protocol.id'], ),
    sa.ForeignKeyConstraint(['linked_experiment_id'], ['log_entry.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('technique_name', sa.String(length=100), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('grantee_email', sa.String(length=150), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('link_token', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['lab_group.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_token')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('linked_experiment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_experiment_id'], ['log_entry.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('change_note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_version')
    op.drop_table('task')
    op.drop_table('share')
    op.drop_table('sample_property')
    op.drop_table('protocol')
    op.drop_table('milestone')
    op.drop_table('group_member')
    op.drop_table('share_comment')
    op.drop_table('sample')
    op.drop_table('project')
    op.drop_table('overlay_plot')
    op.drop_table('misc_entry')
    op.drop_table('log_entry')
    op.drop_table('lab_group')
    op.drop_table('data_file')
    op.drop_table('char_entry')
    op.drop_table('analysis_snapshot')
    op.drop_table('user')
    op.drop_table('image_analysis')
    op.drop_table('feedback')
    op.drop_table('defect_annotation')
    # ### end Alembic commands ###
